### ISSUE TITLE
Refactor template application into SmartyDo

### ISSUE THREAD

**Issue by YesYouKenSpace** [CS2103AUG2016-W10-C3/main#1]
Already working on it at [refactor-addressbook](https://github.com/CS2103AUG2016-W10-C3/main/tree/refactor-addressbook). Making sure that every variable is renamed proper and the documentation.
Person --> Task
Email --> Description
Phone --> Time
Address --> Location
Tags (Unchanged)

**Comment by MoonByunghun** [comment]
I'll try to do some stuff in UI part.

**Comment by kennethtxytqw** [comment]
Already working on it at [refactor-addressbook](https://github.com/CS2103AUG2016-W10-C3/main/tree/refactor-addressbook)

**Comment by YesYouKenSpace** [comment]
I think for now we will just leave the package naming as seedu.address.\* 
I don't think the package name will cause any confusion or anything. What do y'all think?

**Comment by MoonByunghun** [comment]
Yeah, we can change the naming later
