### ISSUE TITLE
Modify Time Class

### ISSUE THREAD

**Issue by YesYouKenSpace** [CS2103AUG2016-W10-C3/main#14]
1. Check Java's implementation of Time and Date. Determine a suitable structure to implement the Time class.
2. Decide how the format of its user input. (Please indicate here as soon as possible and tag a new issue to implement it into the parser class.

**Comment by YesYouKenSpace** [comment]
Use Natty library

**Comment by filbert-c** [comment]
Remove Natty, disastrous to debug
