### ISSUE TITLE
Refactor "magic" variables

### ISSUE THREAD

**Issue by YesYouKenSpace** [CS2103AUG2016-W10-C3/main#24]
1. " " -- the empty string temporarily misused to allow varying arguments in command line

If you used any please add them here. Or remember anything else i missed. @MCHowl @mitigator @MoonByunghun

**Comment by filbert-c** [comment]
Optional class, still currently best practices to use it. But thats what we should use

**Comment by YesYouKenSpace** [comment]
I don't think there is any more magic variables as of now. Closing.
