### ISSUE TITLE
Beautify TaskCard in BrowserPanel (viewResult)

### ISSUE THREAD

**Issue by YesYouKenSpace** [CS2103AUG2016-W10-C3/main#27]

**Comment by MCHowl** [comment]
Current basic implementation can be found in ReadOnlyTask.java , under the function getAsHTML()

**Comment by YesYouKenSpace** [comment]
Putting it on hold as i realised if we were to make it more dynamic it cannot be just static html. We might have to make a new panel just to house this one to make it more dynamic
