### ISSUE TITLE
Implement Recurring Task and Blockouts?

### ISSUE THREAD

**Issue by YesYouKenSpace** [CS2103AUG2016-W10-C3/main#29]
## **Let's finalise our decision by this Friday 15/10/16.**

@MCHowl @mitigator @MoonByunghun 
We need to decide if we should have this? And how.

**Comment by YesYouKenSpace** [comment]
I think we should still have them. The blockouts is sort of what Jim wants even though it isn't a must have. But having them will definitely add flavor to our project, making it easier to present later.

**Comment by filbert-c** [comment]
Blockouts can be implemented using a interval tree. Insert the task to the interval tree and prevent other task from entering that slot for that day.

Eg: Blockout 4pm 6pm.
Insert new task Current date , start time 4pm , end time 6pm

All current task 4pm-6pm transfered to a list with "untimed" in the current day
