### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W10-C3/main#41]
I'm giving you guys one day to do any further updates to the user guide and developer guide (_**if**_ you want to do any further updates based on what I said during the tutorial)  before I review them on GitHub.

**Comment by YesYouKenSpace** [comment]
Yes prof we will do it before tmr 2359. Thank you for the extension.

**Comment by damithc** [comment]
UPDATED: here's the correct feedback:

# Developer Guide
- From the top, 1. Why is this class not connected to anything? 2. Inheritance symbol missing. 3. Overlapping lines makes it hard to understand (where is the dotted line going?) 4. Showing multiplicities can be useful for these parts of a task. 
  ![image](https://cloud.githubusercontent.com/assets/1673303/19548978/17ba25c4-96d4-11e6-8eb8-21ddbc9a64e1.png)
- Storage class diagram not updated.
- Logging levels: content messed up
- You mention UrlUtilTest, but do you even need UrlUtil class? Remove unused classes.
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way. 
  - Similarly, you can explain other interesting design decisions you made.

# User Guide
- Good job adding a lot of screen shots. In future, you might want to use partial screenshots capturing only the part in concern. Otherwise you'll have to update all screenshots when some minor detail of the GUI changes.
- See if you can make the command format easier to type.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by damithc** [comment]
BTW, the person who doesn't have a proper profile picture in the AboutUs.md is going to be penalized. I remember mentioning this once earlier.
